### ISSUE TITLE
Weekly meeting on Feb 6 at 3 p.m. (Room 2323 in Hunt library)

### ISSUE THREAD

**Issue by ChristineTzeng** [genterist/whiteWolf#19]

**Comment by mfarve1** [comment]
Tam, I am having issues with the migration of the swift code from bluemix over to my version of swift on xcode.  bluemix uses an older version of swift which causes problems in my version specifically when using alamofire pod from cocoapads.  So I've started looking at the code in java for android, the java code works but I'm having issues modifying and expanding it because it seem like bluemix generates the code with java classes from their API that are not accessible to me, I assume this would be the same issue with ios swift code.  Let me know what you think we should do,

**Comment by genterist** [comment]
Hi Matt,

Remember I mentioned we will use Objective-C when it comes to iOS ? I tried successfully with Objective C. Just follow the directions regarding cocoapod for objective C and it will work. After the cocoapod steps, you have to open the workspace file, not the project file.

**Comment by mfarve1** [comment]
Are you able to easily modify the code in Objective-C?

**Comment by mfarve1** [comment]
I think i accidentally closed this thread, I'll try with Obj-C and let you know what issues i run into

**Comment by genterist** [comment]
Yes Matt,
We should be able to modify codes in Objective-C.
It's pretty similar to C so if you know C well, you should be able to catch up with Objective-C faster than Swift. ...
I am going to the OpenSource 101 conference... will be back this late afternoon. I also reopen the issue.

**Comment by genterist** [comment]
Team,
Please feel free to add the topics you want to discuss today at the meeting after this post of mine. I just post it here so I won't forget. 

- [x] Review progress

- [x] Discuss DB options

- [x] Collaborate on the cloud and github

- [x] Xcode and Ios issues ?

- [x] Tutorials

- [x] Simulation solution - db animation ?

- [x] Decide time frames

**Comment by ChristineTzeng** [comment]
Note(next task):
Christine: push notifications(if possible, plus server-side implementation)
