### ISSUE TITLE
[Matt - 13FEB] Add Threat Map Buttons

### ISSUE THREAD

**Issue by mfarve1** [genterist/whiteWolf#24]

**Comment by mfarve1** [comment]
@genterist , 

I think the demo's are linked up, I see the changes you are making on my MAC simulation.  ie. you are adding buttons to the TheatMap where I am working.  I now see Emergency room and surgery room on the screen where I am suppose to adding additional rooms.  Im confused now, let me know. 

Matt

**Comment by genterist** [comment]
Matt,

It is because the database was updated. You dont have to manually make the buttons. I think it would be best if you focus on just how to make the mobil screen auto refresh. 
I think there is a little misunderstanding about the buttons. I just need the graphic files (jpegs or png). If you want, we can talk more on google hangout tomorrow.

**Comment by mfarve1** [comment]
Tam, 

Yea because the way its setup now we are only providing an overview threat of the Emergency room, Surgery room, and patient check-in, Originally the treat map visually show the threat level associated for each room not just a section of the hospital.  

Their was no confusion Wednesday when we met, the issues is labeled add threat map buttons which we talked about, not find jpegs and png. Yea I'll be available tomorrow afternoon we can do a google hangout to figure this out.  

Matt

**Comment by genterist** [comment]
Matt,

The jpgs or pngs will be used as threat level indicator. On the app, if you click to the button, you will see the stats of the rooms.
I am working on database and making some changes to test. We'll talk more tomorrow.
